using Rassoodock.Common;

namespace Rassoodock.SqlServer.Models.Domain
{
    public enum DataType
    {
        [Sql("bigint")]
        BinInt,
        [Sql("numeric")]
        Numeric,
        [Sql("bit")]
        Bit,
        [Sql("smallint")]
        SmallInt,
        [Sql("decimal")]
        Decimal,
        [Sql("smallmoney")]
        SmallMoney,
        [Sql("int")]
        Int,
        [Sql("tinyint")]
        TinyInt,
        [Sql("money")]
        Money,
        [Sql("float")]
        Float,
        [Sql("real")]
        Real,
        [Sql("date")]
        Date,
        [Sql("datetimeoffset")]
        DateTimeOffset,
        [Sql("datetime2")]
        DateTime2,
        [Sql("smalldatetime")]
        SmallDateTime,
        [Sql("datetime")]
        DateTime,
        [Sql("time")]
        Time,
        [Sql("char")]
        Char,
        [Sql("varchar")]
        VarChar,
        [Sql("text")]
        Text,
        [Sql("nchar")]
        NChar,
        [Sql("nvarchar")]
        NVarChar,
        [Sql("ntext")]
        NText,
        [Sql("binary")]
        Binary,
        [Sql("varbinary")]
        VarBinary,
        [Sql("image")]
        Image,
        [Sql("cursor")]
        Cursor,
        [Sql("rowversion")]
        RowVersion,
        [Sql("hierarchyid")]
        HierarchyId,
        [Sql("uniqueidentifier")]
        UniqueIdentifier,
        [Sql("xml")]
        Xml,
        [Sql("sqlvariant")]
        SqlVariant,
        [Sql("table")]
        Table

    }
}